name: task_mgmnt_system
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.2
  dartz: ^0.10.1
  dio: ^5.6.0
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_native_splash: ^2.3.7
  geolocator: ^11.1.0
  get: ^4.6.5
  hive_flutter: ^1.1.0
  http: ^1.1.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  path_provider_android: ^2.2.2
  path_provider_ios: ^2.0.15 # Add this for iOS support
  path_provider: ^2.0.15 # Ensures compatibility with Android and iOS
  hive: ^2.2.3 # Include hive core package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/splash.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo.png
